from __future__ import annotations

from typing import Any

from pydantic import TypeAdapter

try:
    from .api_models import (
        ErrorResponse,
        EventStreamResponse,
        LocalEventItem,
        LocalEventRuntimeInfo,
        LocalEventSearchRequest,
        LocalEventSearchResponse,
        LocalEventSourceDebug,
        LocalEventSourceSummary,
        MarketConfigRequest,
        MarketConfigResponse,
        MarketRefreshResponse,
        PhotoItem,
        PhotosResponse,
        RuntimeMissingResponse,
        ScheduleItem,
    )
except ImportError:
    from api_models import (
        ErrorResponse,
        EventStreamResponse,
        LocalEventItem,
        LocalEventRuntimeInfo,
        LocalEventSearchRequest,
        LocalEventSearchResponse,
        LocalEventSourceDebug,
        LocalEventSourceSummary,
        MarketConfigRequest,
        MarketConfigResponse,
        MarketRefreshResponse,
        PhotoItem,
        PhotosResponse,
        RuntimeMissingResponse,
        ScheduleItem,
    )

OPENAPI_VERSION = "3.1.0"


def schema_for(model: Any) -> dict[str, Any]:
    return model.model_json_schema(ref_template="#/components/schemas/{model}")


def list_schema_for(item_type: Any) -> dict[str, Any]:
    return TypeAdapter(list[item_type]).json_schema(ref_template="#/components/schemas/{model}")


def ref(name: str) -> dict[str, str]:
    return {"$ref": f"#/components/schemas/{name}"}


def one_of(*schemas: dict[str, Any]) -> dict[str, Any]:
    return {"oneOf": list(schemas)}


def json_response(schema: dict[str, Any] | None = None, description: str = "OK") -> dict[str, Any]:
    content: dict[str, Any] = {"application/json": {}}
    if schema is not None:
        content["application/json"]["schema"] = schema
    return {"description": description, "content": content}


def request_body(schema: dict[str, Any], required: bool = True) -> dict[str, Any]:
    return {"required": required, "content": {"application/json": {"schema": schema}}}


def build_openapi() -> dict[str, Any]:
    schedule_list_schema = list_schema_for(ScheduleItem)
    object_schema = {"type": "object", "additionalProperties": True}
    local_event_read_schema = one_of(
        ref("LocalEventSearchResponse"),
        ref("RuntimeMissingResponse"),
    )
    decision_schema = {
        "type": "object",
        "additionalProperties": False,
        "required": ["candidate_id", "decision"],
        "properties": {
            "candidate_id": {
                "type": "string",
                "description": (
                    "Candidate ID. The List Page decision endpoint also accepts the "
                    "validated preview-review-v1: envelope generated by Studio. Its "
                    "candidate identities and original/final URLs must exactly match the "
                    "latest unexpired server Preview manifest before all REAL EVENT / "
                    "NOT EVENT selections and the List Page decision are committed."
                ),
            },
            "decision": {"type": "string", "enum": ["pending", "confirmed", "rejected"]},
        },
    }
    manual_listing_schema = {
        "type": "object",
        "additionalProperties": False,
        "required": ["source_id", "url"],
        "properties": {
            "source_id": {
                "type": "string",
                "description": "Configured institution ID selected by the global institution control.",
            },
            "url": {
                "type": "string",
                "format": "uri",
                "description": "Official HTTP/HTTPS Event listing page on the institution allow-list.",
            },
        },
    }
    preview_listing_schema = {
        "type": "object",
        "additionalProperties": False,
        "required": ["listing_url"],
        "properties": {
            "listing_url": {
                "type": "string",
                "format": "uri",
                "description": "Saved Review list-page URL to preview in isolation, regardless of its current decision.",
            },
        },
    }

    return {
        "openapi": OPENAPI_VERSION,
        "info": {
            "title": "InfoScreen Local API",
            "version": "0.2.3",
            "description": "Local kiosk API for runtime dashboard JSON, refresh actions, market config, local event search, and Local Event operator review.",
        },
        "servers": [{"url": "http://127.0.0.1:8765", "description": "Surface kiosk server; replace 127.0.0.1 with the Surface LAN address when using another trusted device"}],
        "tags": [
            {"name": "dashboard", "description": "Static dashboard and runtime JSON"},
            {"name": "market", "description": "Market config and refresh APIs"},
            {"name": "local-events", "description": "Rendered DOM local event search APIs"},
            {"name": "local-event-review", "description": "Operator review and diagnostics APIs"},
            {"name": "media", "description": "Photo wall media endpoints"},
        ],
        "paths": {
            "/": {"get": {"tags": ["dashboard"], "summary": "Serve dashboard HTML", "description": "Returns the committed dashboard HTML.", "responses": {"200": {"description": "HTML dashboard"}}}},
            "/index.html": {"get": {"tags": ["dashboard"], "summary": "Serve dashboard HTML", "description": "Same as GET /.", "responses": {"200": {"description": "HTML dashboard"}}}},
            "/openapi.json": {"get": {"tags": ["dashboard"], "summary": "Return OpenAPI specification", "responses": {"200": json_response(None)}}},
            "/docs": {"get": {"tags": ["dashboard"], "summary": "Serve Swagger UI", "responses": {"200": {"description": "Swagger UI HTML"}}}},
            "/schedule.json": {"get": {"tags": ["dashboard"], "summary": "Read schedule runtime JSON", "responses": {"200": json_response(schedule_list_schema)}}},
            "/weather.json": {"get": {"tags": ["dashboard"], "summary": "Read weather runtime JSON", "responses": {"200": json_response(object_schema)}}},
            "/market.json": {"get": {"tags": ["market"], "summary": "Read market runtime JSON", "responses": {"200": json_response(object_schema)}}},
            "/market_config.json": {"get": {"tags": ["market"], "summary": "Read market config runtime JSON", "responses": {"200": json_response(ref("MarketConfigResponse"))}}},
            "/event_stream.json": {"get": {"tags": ["dashboard"], "summary": "Read event stream runtime JSON", "responses": {"200": json_response(ref("EventStreamResponse"))}}},
            "/photos.json": {"get": {"tags": ["media"], "summary": "Read photo wall runtime JSON", "responses": {"200": json_response(ref("PhotosResponse"))}}},
            "/sync_status.json": {"get": {"tags": ["dashboard"], "summary": "Read sync status runtime JSON", "responses": {"200": json_response(object_schema)}}},
            "/local_event_search_results.json": {"get": {"tags": ["local-events"], "summary": "Read local event runtime JSON", "description": "Missing runtime data is returned as a 200 JSON error/default shape; HEAD uses 404 for freshness checks.", "responses": {"200": json_response(local_event_read_schema)}}},
            "/api/market-config": {
                "get": {"tags": ["market"], "summary": "Read active market symbol config", "responses": {"200": json_response(ref("MarketConfigResponse"))}},
                "post": {"tags": ["market"], "summary": "Update active market symbol config", "requestBody": request_body(ref("MarketConfigRequest")), "responses": {"200": json_response(ref("MarketConfigResponse")), "400": json_response(ref("ErrorResponse"), "Invalid request")}},
            },
            "/api/market-refresh": {"post": {"tags": ["market"], "summary": "Refresh Market and Weather runtime data", "description": "Runs surface/fetch_live_data.py and returns both runtime payloads.", "responses": {"200": json_response(ref("MarketRefreshResponse")), "500": json_response(one_of(ref("MarketRefreshResponse"), ref("ErrorResponse")), "Producer failed or could not start")}}},
            "/api/local-events/search": {
                "get": {"tags": ["local-events"], "summary": "Read latest local event search results", "description": "Returns runtime JSON without running a new search. Missing data is represented in a 200 JSON payload.", "responses": {"200": json_response(local_event_read_schema)}},
                "post": {"tags": ["local-events"], "summary": "Run local event search for a location", "description": "Runs surface/search_local_events.py. The supported entrypoint forces Chromium to start with --disable-http2.", "requestBody": request_body(ref("LocalEventSearchRequest")), "responses": {"200": json_response(ref("LocalEventSearchResponse")), "500": json_response(one_of(ref("LocalEventSearchResponse"), ref("ErrorResponse")), "Search failed"), "504": json_response(ref("LocalEventSearchResponse"), "Search exceeded the HTTP timeout")}},
            },
            "/api/local-events/review/state": {
                "get": {"tags": ["local-event-review"], "summary": "Read Local Event review state", "description": "Returns configured institutions, list-page decisions, Event candidates, diagnostics, and submitted positions from surface/.env/local_event_review/state.json. The latest Preview exact-set manifest is process-local and is not returned by this endpoint.", "responses": {"200": json_response(object_schema), "500": json_response(ref("ErrorResponse"), "State read failed")}},
            },
            "/api/local-events/review/discover-listings": {
                "post": {"tags": ["local-event-review"], "summary": "Discover candidate official list pages", "description": "Runs Playwright against the selected configured institution home page. Chromium starts with --disable-http2 and performs no HTTP/2-first retry. A no-longer-discovered non-manual page is retired together with its committed Preview selection; a failed Review-state write restores the previous selection file, and successful retirement invalidates the process-local Preview manifest.", "responses": {"200": json_response(object_schema), "500": json_response(ref("ErrorResponse"), "Discovery failed")}},
            },
            "/api/local-events/review/listing-page": {
                "post": {"tags": ["local-event-review"], "summary": "Add one operator-supplied official Event list page", "description": "Validates the selected institution and allowed official domain, saves the page as pending review state, and does not collect Events automatically. Adding the same URL resets it to pending and removes its old committed Preview selection and process-local manifest. The saved page may be previewed before a decision; normal persisted collection requires a confirmed page with committed REAL EVENT selections.", "requestBody": request_body(manual_listing_schema), "responses": {"200": json_response(object_schema), "400": json_response(ref("ErrorResponse"), "Invalid institution or listing URL")}},
            },
            "/api/local-events/review/listing-decision": {
                "post": {"tags": ["local-event-review"], "summary": "Save a List Page decision and optional Preview selections", "description": "A normal candidate ID updates the List Page decision under the existing compatibility contract. Studio uses a validated preview-review-v1: envelope to commit every REAL EVENT / NOT EVENT selection and the List Page decision in one request. The submitted candidate IDs, original listing links, and final redirected/public URLs must exactly equal the latest unexpired process-local server Preview manifest for the unchanged List Page revision. A service restart, expiry, newer Preview, List Page state change, reset, rejection, manual re-add, or discovery retirement requires a new Preview. Confirmation requires at least one REAL EVENT; a rejected page cannot contain REAL EVENT selections. If the List Page state write fails, the prior Preview selection file is restored and the manifest remains available for retry.", "requestBody": request_body(decision_schema), "responses": {"200": json_response(object_schema), "400": json_response(ref("ErrorResponse"), "Invalid decision, candidate set, or missing/expired/superseded Preview manifest")}},
            },
            "/api/local-events/review/preview-events": {
                "post": {"tags": ["local-event-review"], "summary": "Preview Event candidates from one saved list page", "description": "Accepts a pending, confirmed, or rejected saved list page. The server copies Review state into an isolated temporary store, marks only that copy confirmed, clears copied Events and feedback, runs the final Preview collector and detail owner, completes redirect/detail enrichment, then records the exact returned candidate set in a process-local manifest. The manifest defaults to a 21,600-second lifetime with a 60-second minimum and is controlled by INFOSCREEN_PREVIEW_MANIFEST_TTL_SECONDS. Preview does not change persisted Review state. Candidate choices remain browser-session drafts until a separate List Page decision request commits them; a draft whose manifest is no longer valid must be Previewed again.", "requestBody": request_body(preview_listing_schema), "responses": {"200": json_response(object_schema), "400": json_response(ref("ErrorResponse"), "Missing or unknown listing URL"), "500": json_response(ref("ErrorResponse"), "Preview collection failed")}},
            },
            "/api/local-events/review/collect-events": {
                "post": {"tags": ["local-event-review"], "summary": "Collect selected REAL EVENT candidates from confirmed pages", "description": "Reads confirmed List Pages that have committed REAL EVENT selections, filters unselected listing cards before detail navigation, follows official detail links with the formal HTTP/1 Chromium policy, writes per-listing recognition diagnostics, and persists only selected Event candidates as confirmed. It does not change List Page decisions.", "responses": {"200": json_response(object_schema), "500": json_response(ref("ErrorResponse"), "Collection failed")}},
            },
            "/api/local-events/review/event-decision": {
                "post": {"tags": ["local-event-review"], "summary": "Save an Event candidate review decision", "requestBody": request_body(decision_schema), "responses": {"200": json_response(object_schema), "400": json_response(ref("ErrorResponse"), "Invalid decision")}},
            },
            "/public_photos/{path}": {
                "get": {"tags": ["media"], "summary": "Serve a public photo file", "parameters": [{"name": "path", "in": "path", "required": True, "schema": {"type": "string"}, "description": "Relative path under surface/.env/public_photos/."}], "responses": {"200": {"description": "Photo bytes"}, "404": {"description": "Not found"}}},
                "head": {"tags": ["media"], "summary": "Read public photo metadata", "parameters": [{"name": "path", "in": "path", "required": True, "schema": {"type": "string"}}], "responses": {"200": {"description": "Photo metadata"}, "404": {"description": "Not found"}}},
            },
        },
        "components": {
            "schemas": {
                "ErrorResponse": schema_for(ErrorResponse),
                "RuntimeMissingResponse": schema_for(RuntimeMissingResponse),
                "MarketConfigRequest": schema_for(MarketConfigRequest),
                "MarketConfigResponse": schema_for(MarketConfigResponse),
                "MarketRefreshResponse": schema_for(MarketRefreshResponse),
                "LocalEventSearchRequest": schema_for(LocalEventSearchRequest),
                "LocalEventRuntimeInfo": schema_for(LocalEventRuntimeInfo),
                "LocalEventItem": schema_for(LocalEventItem),
                "LocalEventSourceSummary": schema_for(LocalEventSourceSummary),
                "LocalEventSourceDebug": schema_for(LocalEventSourceDebug),
                "LocalEventSearchResponse": schema_for(LocalEventSearchResponse),
                "EventStreamResponse": schema_for(EventStreamResponse),
                "PhotoItem": schema_for(PhotoItem),
                "PhotosResponse": schema_for(PhotosResponse),
                "ScheduleItem": schema_for(ScheduleItem),
            }
        },
    }


if __name__ == "__main__":
    import json

    print(json.dumps(build_openapi(), ensure_ascii=False, indent=2))
