---
name: full-project-acceptance-hard-gates
description: Generic hard-gated methodology for accepting a complete software project by deriving requirements from a spec, mapping implementation, collecting test/CI/artifact evidence, classifying gaps, and issuing a pass/conditional/fail decision.
---

# Full Project Acceptance Hard Gates

Use this skill when the user asks for a reusable capability to accept a complete software project.

This skill must stay project-agnostic. Do not encode project names, repository names, PR numbers, or domain-specific implementation facts into the skill. Apply the gates to the target project at runtime by reading that project's current requirements, code, tests, workflows, artifacts, and docs.

## Core rule

Do not accept a project because one test is green, one report exists, or one PR was merged.

A project passes only when:

1. the original requirement is converted into a requirement matrix;
2. every major requirement is mapped to current implementation;
3. critical security and access-control behavior is verified separately;
4. test and CI evidence is tied to the target commit;
5. generated artifacts are inspected rather than assumed;
6. probe runs are not confused with full-suite runs;
7. no blocking gate fails.

## Evidence hierarchy

Prefer evidence in this order:

1. Executed test logs and generated artifacts for the target commit.
2. CI workflow runs, job status, and uploaded artifacts.
3. Generated summaries committed by automation.
4. Source code, migrations, configuration, and scripts.
5. Static or contract guard scripts.
6. Product, API, and operations documentation.
7. Manual smoke UI or manual validation surface.
8. User-provided claim.
9. Assistant-written summary.

Assistant-written reports are review summaries only. They are not test artifacts.

## Required report outputs

Any acceptance report using this skill must include:

```text
scope
target commit or branch
original requirement source
requirement matrix
hard gate table
evidence table
artifact table
gap table
final verdict
caveats
```

## Status vocabulary

Use only:

```text
PASS          Requirement is implemented and evidence supports it.
CONDITIONAL   Mostly acceptable, but evidence is incomplete, indirect, or probe-only.
FAIL          Required behavior is missing or contradicted.
NOT VERIFIED  Evidence was unavailable or not checked.
```

## Gap severity

```text
P0 blocker      Cannot accept.
P1 conditional  Accept only with explicit caveat or follow-up.
P2 quality      Non-blocking improvement.
Evidence gap    Implementation may exist, but proof is missing.
Spec gap        Requirement wording needs clarification.
```

Any P0 blocker prevents a final PASS.

# Hard gates

## Gate 0: Evidence provenance

Must check:

- target repository or source package;
- target branch, tag, or commit;
- latest relevant changes;
- whether evidence belongs to the target code revision;
- whether a report was generated by tests/CI or by a reviewer.

PASS requires every material evidence item to be tied to a commit, run, artifact, log, or file path.

FAIL if old conclusions are reused without rechecking current code, or if a reviewer-written report is presented as a test artifact.

## Gate 1: Requirement coverage

Must check:

- original prompt/spec exists;
- every major product requirement is converted into an atomic checklist item;
- requirements are grouped by category;
- no major requirement is silently skipped.

Required categories:

```text
architecture
runtime and deployment
data model and persistence
storage
API contract
workflow or state machine
access control and security
authentication and session behavior
protected data and response masking
domain features
audit and observability
notifications or asynchronous side effects, if required
backup, restore, and operations
UI or manual validation, if required
documentation
tests, CI, and artifacts
```

PASS requires a requirement matrix with evidence for each major item.

FAIL if a final verdict is issued without a requirement matrix.

## Gate 2: Architecture and deployment

Must check:

- required language, framework, and runtime;
- required persistence technology;
- required file/object storage model;
- packaging or deployment files;
- runtime assets copied into the deployable artifact;
- external dependency posture;
- startup/build evidence.

Evidence sources may include build files, dependency manifests, bootstrap code, migrations, Docker/deployment files, and runtime acceptance logs.

FAIL if the required architecture is absent or the system cannot build/start in the required runtime model.

## Gate 3: Data model and persistence

Must check:

- required entities exist;
- schema constraints enforce core rules;
- source-of-truth fields are clear;
- version/history/audit tables exist when required;
- write paths align with schema;
- compatibility fields are not mistaken for source-of-truth fields.

FAIL if required data cannot be persisted or core constraints are missing.

## Gate 4: Authentication, session, and replay controls

Must check, when applicable:

- password or credential handling;
- failed-auth lockout;
- session/token creation;
- session expiration;
- token revocation;
- request freshness;
- replay protection;
- positive and negative tests or contract checks.

FAIL if only the happy path is verified for authentication/session behavior.

## Gate 5: Protected data and sensitive-field handling

Must check every sensitive field named or implied by the spec.

For each field, verify:

```text
classification
schema/storage location
write path
read/decode/decrypt path
API exposure and masking
test or static contract
```

For encryption or protected-storage claims, verify:

```text
algorithm or helper exists
key source or derivation exists
protected format or prefix exists, if applicable
write path stores protected value
read path opens it only where allowed
plain compatibility field is not source of truth
test or static check guards the behavior
```

FAIL if the spec requires protected storage but the current write path stores sensitive plaintext as source of truth.

## Gate 6: RBAC and field visibility

Must check:

- all roles or principals required by the spec;
- allowed actions by role;
- forbidden actions by role;
- object-level access;
- sensitive fields visible/hidden by role;
- internal/ciphertext/helper fields not serialized;
- positive and negative tests.

Required matrix:

```text
Role | Allowed actions | Forbidden actions | Visible fields | Hidden fields | Evidence
```

FAIL if only positive access paths are tested.

## Gate 7: Workflow and immutability

Must check, when applicable:

- required states exist;
- valid transitions are enforced;
- invalid transitions are rejected;
- terminal states are immutable;
- history records are written;
- audit records are written;
- tests cover valid and invalid paths.

FAIL if terminal immutability or invalid transition rejection is required but unenforced.

## Gate 8: Domain feature completeness

For every domain feature in the spec, verify:

```text
API endpoint or command
service or domain logic
storage mutation
side effects
error handling
positive tests
negative tests
artifact or log evidence
```

FAIL if a core domain feature is only documented but not implemented.

## Gate 9: Audit, notification, and configuration side effects

Must check, when applicable:

- mutating actions write audit events;
- audit metadata is protected when sensitive;
- notifications or side effects are created for required events;
- acknowledgement/read behavior exists when required;
- templates/configuration/workflow dictionaries are editable when required;
- management paths are protected by appropriate authorization.

FAIL if required audit or side effects exist only for some mutating flows without documented exception.

## Gate 10: API contract, errors, and pagination

Must check:

- OpenAPI or equivalent API contract generation;
- route coverage;
- status code coverage;
- request and response schemas;
- authentication annotations;
- uniform error envelope;
- pagination defaults and hard maximums;
- contract tests or static checks.

FAIL if generated API docs are missing for required routes or error contract is inconsistent.

## Gate 11: Backup, restore, and operations

Must check, when required:

- scheduled backup behavior;
- backup artifact creation;
- restore endpoint or documented restore procedure;
- disaster recovery or point-in-time recovery documentation;
- configuration for schedule and paths;
- tests or contracts for backup behavior.

FAIL if backup/restore is a requirement but only mentioned in docs with no runnable mechanism or procedure.

## Gate 12: Local test entrypoints

For every local test script, record:

```text
normal command
probe or contract command
required services
output directory
summary files
HTML or report files
logs
exit behavior
stage list
```

Hard distinction:

```text
full local run     = complete local acceptance evidence
probe/contract run = entrypoint or report-generation evidence only
```

FAIL if probe evidence is reported as full-suite evidence.

## Gate 13: Full regression

Must check full regression separately from local tests.

Required checks:

- full regression script exists;
- stage list is known;
- summary JSON or Markdown is generated;
- CI, merge queue, post-merge, or manual workflow runs it;
- runtime/build acceptance is included when required;
- artifacts or committed summaries are available.

PASS requires a generated summary showing overall pass or equivalent.

## Gate 14: CI workflow and artifact handling

Must check:

- workflow triggers;
- path filters;
- skipped jobs;
- job conclusions;
- artifact upload paths;
- retention;
- failure artifact behavior;
- whether artifacts are downloadable;
- whether the downloaded artifact matches the claimed command.

FAIL if the relevant job was skipped but the report calls that area passed.

## Gate 15: Manual UI or smoke surface

If a manual validation surface is required, check:

- UI/smoke file exists;
- app serves it;
- deployable/runtime artifact includes it;
- it exercises critical flows;
- scope is clear: manual aid vs production UI.

FAIL if a user-facing or manual validation surface is required but neither implemented nor explicitly out of scope.

## Gate 16: Documentation

Must check:

- setup/run docs;
- configuration docs;
- API docs;
- backup/restore/operation docs;
- security model docs;
- test/acceptance docs;
- known limitations.

FAIL if docs contradict current code on critical behavior.

## Gate 17: Final verdict

Before final verdict, produce:

```text
hard gate table
requirement coverage table
test evidence table
artifact provenance table
gap severity table
final pass, conditional, or fail statement
```

Final PASS is allowed only if all P0 gates pass.

# Required report template

```markdown
# Full Project Acceptance Report

## Scope
- Repository/source:
- Branch/commit:
- Original requirement source:
- Runtime target:
- Timestamp:

## Executive verdict
- Verdict: PASS / CONDITIONAL / FAIL
- Reason:
- Blocking gaps:
- Caveats:

## Requirement matrix
| ID | Requirement | Category | Implementation | Evidence | Status | Gap |
|---|---|---|---|---|---|---|

## Hard gate results
| Gate | Name | Status | Evidence | Gap |
|---|---|---|---|---|

## Test and artifact evidence
| Source | Command/workflow | Full/probe | Result | Artifact/log |
|---|---|---|---|---|

## Security and access-control evidence

## API, docs, deployment, and UI evidence

## Gaps
| Severity | Gap | Required fix/evidence |
|---|---|---|

## Final decision
```

# Anti-false-acceptance checklist

```text
[ ] Original requirements reconstructed
[ ] Current code checked
[ ] Requirement matrix complete
[ ] Hard gates evaluated
[ ] Security checked separately
[ ] RBAC denied paths checked
[ ] CI skipped jobs inspected
[ ] Artifacts downloaded or parsed when available
[ ] Probe vs full-suite distinguished
[ ] Assistant report not used as test evidence
[ ] Caveats stated clearly
```

If any unchecked item affects a P0 gate, do not issue PASS.
